language: python

matrix:
  include:
    - os: linux
      python: 3.6
    - os: linux
      # Get Python 3.7 from Xenial
      # https://github.com/travis-ci/travis-ci/issues/9815
      python: 3.7
      dist: xenial
    - os: windows
      # Get Python 3.7 from Chocolatey
      language: sh
      python: 3.7
      before_install:
        - choco install python --version 3.7
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel

cache:
  directories:
  - $HOME/.cache/pip

install:
- python -m pip install .[dev]

script:
- python -m pytest
